baseURL = "https://omicron-ai.dev"
languageCode = "en-us"
title = "Omicron AI"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'read the docs'
  homepage_intro = 'Omicron is a minimal framework for the development of intelligent agents.'
  homepage_image = '/images/logo_wide_av.svg'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Omicron is a minimal framework for the development of intelligent agents."
    meta_og_title = "Omicron"
    meta_og_type = "website"
    meta_og_url = "https://omicron-ai.dev"
    meta_og_image = "/images/gallery-1.png"
    meta_og_description = "Omicron is a minimal framework for the development of intelligent agents."
    meta_twitter_card = "summary"
    meta_twitter_site = "@__ielm__"
    meta_twitter_creator = "@__ielm__"

  [params.logo]
      mobile = "/images/icon_black_small.png"
      standard  = "/images/icon_black_small.png"
